### ISSUE TITLE
#EPIC1

### ISSUE THREAD

**Issue by aiThanet** [we-inc/mms-get-a-se#10]
#  **US1-1**
> As a visitor I can register to be a user so that i can easily find a trainer

### Task
- [x] design the register system @me
- [x] design the register front end @me
- [x] code the register system @5730325021-PT 
- [x] code the register front end @5730303121-NT 
- [x] re-check and debug @5730097921-JW 

------

#  **US1-2**
> As a visitor I can login so that i can use services

### Task
- [x] design the login system @me
- [x] design the login front end @me
- [x] code the login system @5730337521-PC 
- [x] code the login front end @me
- [x] recheck and debug @5730241921-TS 

------

#  **US1-3**
> As a visitor I can search any services that rely on the filter I choose so that I can view any services that I'm interested in

### Task
- [x] Team meeting about service searching @5730684221-AB 
- [x] design the service searching system @5730241921-TS 
- [x] design the service searching front end @5730325021-PT 
- [x] code the service searching system @5730097921-JW 
- [x] code the service searching front end @5730337521-PC 
- [x] recheck and debug @5730303121-NT

**Comment by aiThanet** [comment]
Complete!
